name: ebytr-prod
services:
  ebytr:
    build: reverse-proxy
    ports:
      - 80:80
    depends_on:
      api:
        condition: service_healthy
      ui:
        condition: service_healthy
    restart: always

  ui:
    build: 
      context: ui
      target: production
    ports:
      - 80
    environment:
      - VITE_BACKEND=api:3001
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:80"]
      interval: 3s
      timeout: 10s
      retries: 5

  api:
    build: 
      context: api
      target: production
    ports:
      - 3001
    environment:
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      interval: 3s
      timeout: 10s
      retries: 5

  db:
    image: mongo:5
    ports:
      - 27017
    restart: always
    healthcheck:
      test: ["CMD", "pgrep", "mongod"]
      interval: 3s
      timeout: 10s
      retries: 5
