name: ebytr-dev
services:
  ebytr:
    build: 
      context: reverse-proxy
      args:
        NGINX_CONFIG_FILE: dev.conf
    ports:
      - 3000:3000
      - 3002:3002
    depends_on:
      api:
        condition: service_healthy
      ui:
        condition: service_healthy
    restart: always

  ui:
    build: 
      context: ui
      target: development
    ports:
      - 3000
      - 3002
    command: yarn vite -c vite.config.docker.ts
    volumes:
      - ./ui/src:/app/src
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      interval: 3s
      timeout: 10s
      retries: 5

  api:
    build: 
      context: api
      target: development
    ports:
      - 3001
    command: yarn dev
    volumes:
      - ./api/src:/app/src
    environment:
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      interval: 3s
      timeout: 10s
      retries: 5

  db:
    image: mongo:5
    ports:
      - 27017
    restart: always
    healthcheck:
      test: ["CMD", "pgrep", "mongod"]
      interval: 3s
      timeout: 10s
      retries: 5
