on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Verifica o repositório do Git
        uses: actions/checkout@v2

      - name: Instalando o node com a versão
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Instalando as dependências
        run: yarn

      - name: Executando linter
        run: yarn lint

      - name: Executando testes unitários
        run: yarn test
